# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4dd951ee86b0dd45287caaf88ec92d1ad9d7d78b7d46804d866b5c2c3633c55ff3aca43888457aa16c07075df395a6a4f34d79042d30c4c1af068acda287cc9

test:
  secret_key_base: e68d9c533186c79879318ebb8c58d94dba4fe06d74dc73bbf81d60e81805e175eddff4a1b3c2673dd27f63df16e1cf89a3fbabea70f4d703eb24c5c009ae4c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
